# Exploring Numpy Documentation

https://numpy.org/doc/stable/user/quickstart.html

***

In [23]:
import numpy as np

<br>
Range() & Numpy Arange() functions

In [24]:
# params = lower, upper, increments
list(range(1, 7, 2))

[1, 3, 5]

<br>
Similar to range(), however, Numpy arange() can take in floating point numbers

In [28]:
x = np.arange(1.5, 10, 1.6)

[1.5 3.1 4.7 6.3 7.9 9.5]


In [26]:
# arange recognises the object types given and stores as 64 bit floating number
x.dtype

dtype('float64')

<br>
Shape is a tuple
Eg: (3, 5) where 3 is the first dimension and 5, the second. This would be 3 rows and 5 columns. 

In [29]:
# Shape of x
x.shape

(6,)

<br>
reshape()

<br>
arange creates a list of 15 items 0-14 inclusive. Reshape makes 3 lists of 5 items. 

In [34]:
a = np.arange(15).reshape(3, 5)
print(a)
a.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [35]:
# A tuple of lists with one item in each list       
x.reshape(-1, 1)

array([[1.5],
       [3.1],
       [4.7],
       [6.3],
       [7.9],
       [9.5]])

<br>
To get the square of items in an array:

In [37]:
y = x**2
y

array([ 2.25,  9.61, 22.09, 39.69, 62.41, 90.25])

np.linspace()
Params = start value, end value, no of points between those values
Inclusive of end value

In [40]:
np.linspace(0.0, 10.0, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [41]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
I = np.eye(3)

In [54]:
I.dtype

dtype('float64')

In [56]:
# Not working - suppose to convert type of array items to integers
I.astype('int64')
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Slicing